language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
# command to install requirements
install: 
 - pip install pyflakes pep8 coverage python-coveralls
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py install
# command to run tests
script:
 - pep8 urlarchivefield
 - pyflakes urlarchivefield
 - coverage run setup.py test
after_success:
  - coveralls
